### ISSUE TITLE
tabulate, csv export error!!

### ISSUE THREAD

**Issue by Tongae-Park** [tabulate/tabulate#9]
help me!
I use tabulate (version 0.11.1) from WordPress.
- Wordpress: Version 4.2.2.
- phpMyAdmin : Version 2.11.5.1
- PHP: Version 5.5.17p1.

I export the data to a csv an error occurs, such as the image below.
![- -1](https://cloud.githubusercontent.com/assets/12743365/7978669/eadc33be-0ad2-11e5-8218-24825f5e7b7b.jpg)

**Comment by samwilson** [comment]
Sorry about this!

This might be because your web server user doesn't have access to write to `/tmp`.

Or because youre database user doesn't have [FILE privilege](https://dev.mysql.com/doc/refman/5.7/en/privileges-provided.html#priv_file) (this is a global permission).

I'll add some diagnostic code to help debug this. Thanks for reporting the issue!

**Comment by Tongae-Park** [comment]
I can very well use the software you develop.
If I can speak English well, I'd better be able to deliver you a thankful heart ...
Thank you, thank you again.

**Comment by samwilson** [comment]
I'm glad it worked out. :)

Let me know if you have any other issues with Tabulate!
